### ISSUE TITLE
vanilla crafting table crashes the game

### ISSUE THREAD

**Issue by KaziiTheAvali** [hammy3502/immersive-mc#117]
i placed down a vanilla crafting table and now my world crashes whenever I enter it. removing the mod fixes it. idk how this happens or whats causing it if you have any more asks plz tell me

**Comment by KaziiTheAvali** [comment]
```
[17:27:07] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:crafting_table}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.18.2-20220404.173914-srg.jar%23371!/:?]
	at net.blf02.immersivemc.client.immersive.ImmersiveCrafting.setHitboxes(ImmersiveCrafting.java:49) ~[immersivemc-1.1.0-forge.jar%23201!/:?]
	at net.blf02.immersivemc.client.immersive.ImmersiveCrafting.initInfo(ImmersiveCrafting.java:38) ~[immersivemc-1.1.0-forge.jar%23201!/:?]
	at net.blf02.immersivemc.client.immersive.ImmersiveCrafting.initInfo(ImmersiveCrafting.java:28) ~[immersivemc-1.1.0-forge.jar%23201!/:?]
	at net.blf02.immersivemc.client.immersive.AbstractImmersive.tick(AbstractImmersive.java:103) ~[immersivemc-1.1.0-forge.jar%23201!/:?]
	at net.blf02.immersivemc.client.subscribe.ClientLogicSubscriber.tickInfos(ClientLogicSubscriber.java:152) ~[immersivemc-1.1.0-forge.jar%23201!/:?]
	at net.blf02.immersivemc.client.subscribe.ClientLogicSubscriber.onClientTick(ClientLogicSubscriber.java:75) ~[immersivemc-1.1.0-forge.jar%23201!/:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-4.10.86-forge.jar%2369!/:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-4.10.86-forge.jar%2369!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%2329!/:?]
	at jdk.proxy3.$Proxy365.tick(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:56) ~[architectury-4.10.86-forge.jar%2369!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler_952_EventHandlerImplClient_event_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:910) ~[forge-1.18.2-40.1.74-universal.jar%23376!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1752) ~[client-1.18.2-20220404.173914-srg.jar%23371!/:?]
	at net.minecraft.client.Minecraft.newRunTick(Minecraft.java:12830) ~[client-1.18.2-20220404.173914-srg.jar%23371!/:?]
	at net.minecraft.client.Minecraft.handler$cao000$replaceTick(Minecraft.java:12727) ~[client-1.18.2-20220404.173914-srg.jar%23371!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java) ~[client-1.18.2-20220404.173914-srg.jar%23371!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23371!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23371!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.74.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
``` 
I think this is the unreported exception that crashed the game.

**Comment by hammy275** [comment]
I know exactly why this happens. I'll have this fixed asap
