### ISSUE TITLE
game crashing 

### ISSUE THREAD

**Issue by SoGoodArt** [hammy3502/immersive-mc#154]
Description: Unexpected error

java.lang.NoClassDefFoundError: net/blf02/vrapi/api/data/IVRData
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4)
	at com.hammy275.immersivemc.client.immersive.info.BarrelInfo.<init>(BarrelInfo.java:18)
	at com.hammy275.immersivemc.client.immersive.ImmersiveBarrel.getNewInfo(ImmersiveBarrel.java:40)
	at com.hammy275.immersivemc.client.immersive.ImmersiveBarrel.getNewInfo(ImmersiveBarrel.java:31)
	at com.hammy275.immersivemc.client.immersive.AbstractBlockEntityImmersive.trackObject(AbstractBlockEntityImmersive.java:81)
	at com.hammy275.immersivemc.client.subscribe.ClientLogicSubscriber.possiblyTrack(ClientLogicSubscriber.java:109)
	at com.hammy275.immersivemc.client.subscribe.ClientLogicSubscriber.onClientTick(ClientLogicSubscriber.java:102)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2.$Proxy136.tick(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$3(EventHandlerImpl.java:55)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$cfj000$onEndTick(MinecraftClient:13973)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1907)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.blf02.vrapi.api.data.IVRData
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.hammy275.immersivemc.client.immersive.info.BarrelInfo.<init>(BarrelInfo.java:18)
	at com.hammy275.immersivemc.client.immersive.ImmersiveBarrel.getNewInfo(ImmersiveBarrel.java:40)
	at com.hammy275.immersivemc.client.immersive.ImmersiveBarrel.getNewInfo(ImmersiveBarrel.java:31)
	at com.hammy275.immersivemc.client.immersive.AbstractBlockEntityImmersive.trackObject(AbstractBlockEntityImmersive.java:81)
	at com.hammy275.immersivemc.client.subscribe.ClientLogicSubscriber.possiblyTrack(ClientLogicSubscriber.java:109)
	at com.hammy275.immersivemc.client.subscribe.ClientLogicSubscriber.onClientTick(ClientLogicSubscriber.java:102)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy136.tick(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$3(EventHandlerImpl.java:55)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$cfj000$onEndTick(class_310.java:13973)

-- Affected level --
Details:
	All players: 1 total; [class_746['imTonk'/130, l='ClientLevel', x=-720.50, y=64.17, z=-410.26]]
	Chunk stats: 1024, 318
	Level dimension: minecraft:overworld
	Level spawn location: World: (-665,87,-365), Section: (at 7,7,3 in -42,5,-23; chunk contains blocks -672,-64,-368 to -657,319,-353), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,-64,-512 to -513,319,-1)
	Level time: 1291059 game time, 1187 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by hammy275** [comment]
Looks like I need to get ImmersiveMC to fully run without `mc-vr-api`. I'll get to work on that. Thanks for bringing this to my attention! :)

Until then, you can work around this issue by installing the `mc-vr-api` mod, even if you aren't in VR.

**Comment by hammy275** [comment]
Thanks again for the report! This issue will be fixed with version 1.2.1, which should release in ~15 mins!
