### ISSUE TITLE
1.19.2 Multiplayer: opening ender chest causes player to crash host.

### ISSUE THREAD

**Issue by BAB-Gaming** [hammy3502/immersive-mc#418]
1.5.0-beta1 [FORGE 1.19.2]
the player is unable to rejoin the game without causing the host to crash

Log with error:
java.lang.IllegalAccessError: class com.hammy275.immersivemc.common.immersive.handler.ChestHandler tried to access private field net.minecraft.world.SimpleContainer.f_19147_ (com.hammy275.immersivemc.common.immersive.handler.ChestHandler is in module immersivemc@1.5.0-beta1 of loader 'TRANSFORMER' @2bd7f686; net.minecraft.world.SimpleContainer is in module minecraft@1.19.2 of loader 'TRANSFORMER' @2bd7f686)
	at TRANSFORMER/immersivemc@1.5.0-beta1/com.hammy275.immersivemc.common.immersive.handler.ChestHandler.makeInventoryContents(ChestHandler.java:37)
	at TRANSFORMER/immersivemc@1.5.0-beta1/com.hammy275.immersivemc.server.immersive.TrackedImmersiveData.getSyncPacket(TrackedImmersiveData.java:35)
	at TRANSFORMER/immersivemc@1.5.0-beta1/com.hammy275.immersivemc.server.immersive.TrackedImmersives.syncDataToClient(TrackedImmersives.java:76)
	at TRANSFORMER/immersivemc@1.5.0-beta1/com.hammy275.immersivemc.server.immersive.TrackedImmersives.trackImmersive(TrackedImmersives.java:72)
	at TRANSFORMER/immersivemc@1.5.0-beta1/com.hammy275.immersivemc.server.immersive.TrackedImmersives.maybeTrackImmersive(TrackedImmersives.java:47)
	at TRANSFORMER/immersivemc@1.5.0-beta1/com.hammy275.immersivemc.server.ServerSubscriber.onPlayerTick(ServerSubscriber.java:43)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at TRANSFORMER/architectury@6.6.92/dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at TRANSFORMER/architectury@6.6.92/dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy121.tick(Unknown Source)
	at TRANSFORMER/architectury@6.6.92/dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:138)
	at TRANSFORMER/architectury@6.6.92/dev.architectury.event.forge.__EventHandlerImplCommon_event_PlayerTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.5/net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:819)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:288)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129483_(Connection.java:248)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Unknown Source)

[18June2024 18:20:40.934] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalAccessError: class com.hammy275.immersivemc.common.immersive.handler.ChestHandler tried to access private field net.minecraft.world.SimpleContainer.f_19147_ (com.hammy275.immersivemc.common.immersive.handler.ChestHandler is in module immersivemc@1.5.0-beta1 of loader 'TRANSFORMER' @2bd7f686; net.minecraft.world.SimpleContainer is in module minecraft@1.19.2 of loader 'TRANSFORMER' @2bd7f686)
	at com.hammy275.immersivemc.common.immersive.handler.ChestHandler.makeInventoryContents(ChestHandler.java:37) ~[immersivemc-1.5.0-beta1-1.19.2-forge.jar%23283!/:?]
	at com.hammy275.immersivemc.server.immersive.TrackedImmersiveData.getSyncPacket(TrackedImmersiveData.java:35) ~[immersivemc-1.5.0-beta1-1.19.2-forge.jar%23283!/:?]
	at com.hammy275.immersivemc.server.immersive.TrackedImmersives.syncDataToClient(TrackedImmersives.java:76) ~[immersivemc-1.5.0-beta1-1.19.2-forge.jar%23283!/:?]
	at com.hammy275.immersivemc.server.immersive.TrackedImmersives.trackImmersive(TrackedImmersives.java:72) ~[immersivemc-1.5.0-beta1-1.19.2-forge.jar%23283!/:?]
	at com.hammy275.immersivemc.server.immersive.TrackedImmersives.maybeTrackImmersive(TrackedImmersives.java:47) ~[immersivemc-1.5.0-beta1-1.19.2-forge.jar%23283!/:?]
	at com.hammy275.immersivemc.server.ServerSubscriber.onPlayerTick(ServerSubscriber.java:43) ~[immersivemc-1.5.0-beta1-1.19.2-forge.jar%23283!/:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.6.92-forge.jar%23248!/:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-6.6.92-forge.jar%23248!/:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar%23117!/:?]
	at jdk.proxy3.$Proxy121.tick(Unknown Source) ~[?:?]
	at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:138) ~[architectury-6.6.92-forge.jar%23248!/:?]
	at dev.architectury.event.forge.__EventHandlerImplCommon_event_PlayerTickEvent.invoke(.dynamic) ~[architectury-6.6.92-forge.jar%23248!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%23116!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23116!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23116!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:819) ~[forge-1.19.2-43.3.5-universal.jar%23330!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:288) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23325!/:?]
	... 6 more

**Comment by hammy275** [comment]
That's an extremely odd bug, thank you for reporting it :)

**Comment by hammy275** [comment]
Thank you for reporting this! It is fixed now, and the fix will come with the next version of ImmersiveMC (1.5.0 Beta 2)!
